import Head from "next/head";

export default function Home() {
  return (
    <div>
      {/* TODO: this head */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Build your page here</div>
    </div>
  );
}
