import Head from "next/head";
import React, { Component } from "react";
import Content from "../src/collections/contents/Content";
import ContentPanel from "../src/collections/contents/ContentPanel";
import styles from "../styles/Home.module.css";

class Home extends Component {
  state = { contents: [], page: { showBoxShadow: false } };

  async componentDidMount() {
    window.addEventListener("scroll", this.handleScroll);

    const contents = await Content.query();
    this.setState({ contents });
  }

  componentWillUnmount() {
    window.removeEventListener("scroll", this.handleScroll);
  }

  handleScroll = () => {
    const { page } = this.state;
    if (!page.showBoxShadow && window.scrollY > 40)
      this.setState({ page: { showBoxShadow: true } });
    if (page.showBoxShadow && window.scrollY < 40)
      this.setState({ page: { showBoxShadow: false } });
  };

  render() {
    const { contents, page } = this.state;

    return (
      <div>
        {/* TODO: this head */}
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.page}>
          <div
            className={styles.navbar}
            style={{
              boxShadow: page.showBoxShadow ? "0px 3px #2A2828" : "none",
            }}
          >
            <div className={styles.button}>Home</div>
            <div className={styles.input}>
              <input placeholder="search"></input>
            </div>
            <div className={styles.button}></div>
            <div className={styles.button}></div>
          </div>
          <div className={styles.container}>
            <ContentPanel contents={contents} />
          </div>
        </div>
      </div>
    );
  }
}

export default Home;
