import Head from "next/head";
import React, { useState } from "react";
import Content from "../src/entity/content/Content";

export default function Home() {
  const [content, setContent] = useState(
    Content.get({
      id: 0,
      type: "class",
    })
  );

  return (
    <div>
      {/* TODO: this head */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <content.Card content={content} />
      <button
        onClick={() => {
          setContent({ ...content, id: content.id + 1 });
        }}
      >
        TESTE
      </button>
      <div>Build your page here</div>
    </div>
  );
}
