import Head from "next/head";
import React, { useEffect, useState } from "react";
import Content from "../src/collections/contents/Content";
import ContentPanel from "../src/collections/contents/ContentPanel";

export default function Home() {
  const [contents, setContents] = useState([]);

  useEffect(() => {
    (async () => {
      const contents = await Content.query();
      setContents(contents);
    })();
  }, []);

  return (
    <div>
      {/* TODO: this head */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ height: "100vh", width: "100vw", overflow: "auto" }}>
        <ContentPanel contents={contents} />
      </div>
    </div>
  );
}
